# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feasta', '0003_guestadd_summerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('bf', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('date', models.DateField(db_index=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummerRegistrationPickDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_time', models.DateTimeField(auto_now_add=True)),
                ('dates', models.TextField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bulkredemption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bulkredemption',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='bulkredemption',
            name='endmeal',
        ),
        migrations.RemoveField(
            model_name='bulkredemption',
            name='startmeal',
        ),
        migrations.AlterUniqueTogether(
            name='redemption',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='redemption',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='meal',
        ),
        migrations.DeleteModel(
            name='BulkRedemption',
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
        migrations.AlterUniqueTogether(
            name='absent',
            unique_together=set([('booked_by', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='absent',
            index_together=set([('booked_by', 'date')]),
        ),
    ]
