# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0006_auto_20161105_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('typeOfProject', models.TextField()),
                ('supervisors', models.TextField()),
                ('year', models.TextField()),
                ('summer', models.TextField()),
                ('is_taken', models.BooleanField(default=False)),
                ('students', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 16, 38, 48, 417999, tzinfo=utc)),
        ),
    ]
