# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0008_auto_20161114_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='code_verbose',
            field=models.CharField(default=b'EX', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='next_code_int',
            field=models.CharField(default=b'001', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.TextField(default='001'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 13, 47, 28, 487317, tzinfo=utc)),
        ),
    ]
