# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0009_auto_20161117_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_up', models.FileField(upload_to=b'/static/files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 18, 5, 20, 31, 16782, tzinfo=utc)),
        ),
    ]
