# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0010_auto_20161118_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btpstudent',
            name='btpproject',
        ),
        migrations.RemoveField(
            model_name='btpstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='honorsstudent',
            name='honorsproject',
        ),
        migrations.RemoveField(
            model_name='honorsstudent',
            name='user',
        ),
        migrations.AlterField(
            model_name='btpprojectgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Project'),
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 18, 8, 32, 24, 415275, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='BTPProject',
        ),
        migrations.DeleteModel(
            name='BTPStudent',
        ),
        migrations.DeleteModel(
            name='HonorsProject',
        ),
        migrations.DeleteModel(
            name='HonorsStudent',
        ),
    ]
