# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0011_auto_20161118_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 18, 12, 38, 42, 584151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file_up',
            field=models.FileField(upload_to=b'static/files/'),
        ),
    ]
