# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0013_auto_20161125_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('typeOfProject', models.TextField()),
                ('supervisors', models.TextField()),
                ('year', models.TextField()),
                ('summer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 25, 13, 59, 22, 449864, tzinfo=utc)),
        ),
    ]
