# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0014_auto_20161125_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarchives',
            name='restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 11, 27, 10, 29, 16, 88765, tzinfo=utc)),
        ),
    ]
