# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0015_auto_20161127_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 5, 38, 40, 439645, tzinfo=utc)),
        ),
    ]
