# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0016_auto_20170111_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 5, 42, 37, 727252, tzinfo=utc)),
        ),
    ]
