# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0017_auto_20170111_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 10, 5, 44, 78968, tzinfo=utc)),
        ),
    ]
