# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0018_auto_20170114_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 1, 15, 5, 39, 36, 221934, tzinfo=utc)),
        ),
    ]
