# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0019_auto_20170115_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 13, 47, 5, 758542, tzinfo=utc)),
        ),
    ]
