# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0020_auto_20170201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2017, 2, 3, 13, 44, 17, 77939, tzinfo=utc)),
        ),
    ]
