# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0021_auto_20170203_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btpsetweek',
            name='evalday',
        ),
    ]
