# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTPLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=150)),
                ('expired', models.BooleanField(default=False)),
                ('reset_request_time', models.DateTimeField(auto_now_add=True)),
                ('last_access_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
