# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='upvotes',
        ),
    ]
