# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp', '0004_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradedIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='posted_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='upgradedissues',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gp.Complaint'),
        ),
        migrations.AddField(
            model_name='upgradedissues',
            name='upgraded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
