# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_auto_20160405_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradedissues',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='upgradedissues',
            name='upgraded_by',
        ),
        migrations.DeleteModel(
            name='UpgradedIssues',
        ),
    ]
