# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_upvotetracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='who_can_see',
        ),
    ]
