# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0009_auto_20160406_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotetracker',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='upvotetracker',
            name='user',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='cid',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='uid',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set([('complaint', 'user')]),
        ),
        migrations.DeleteModel(
            name='UpvoteTracker',
        ),
    ]
