# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_auto_20160407_0027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set([]),
        ),
    ]
