# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_auto_20160407_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
