# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(default='Not Description Available')),
                ('link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
